### ISSUE TITLE
Reading defaults file doesn't cover quoted passwords

### ISSUE THREAD

**Issue by techwolf359** [sjmudd/ps-top#11]
In a `~/.my.cnf` file, you can enclose passwords with special characters within quotes, as

```
password="%@%GT@@gf54%@"
```
(no this is not my password)

The parser doesn't interpret single or double quotes correctly with password. That is, it tries to send the quotes as part of the password.

Reproduce by enclosing password with single or double quote and get an error connecting. Remove quotes and it works.

**Comment by sjmudd** [comment]
This issue has been resolved recently. Please try v1.0.0 or later and see if resolves your issue.
