### ISSUE TITLE
Unknown column 'SUM_TIMER_WAIT' in 'field list'

### ISSUE THREAD

**Issue by scorredoira** [sjmudd/ps-top#4]
Hi Simon,

I am trying to run the tool but I get the error:

     2015/10/18 19:45:19 Error 1054: Unknown column 'SUM_TIMER_WAIT' in 'field list'

and the program exits.

I am using mysql 5.5 with performance enabled and accessing as root

	+-------------------------+-----------------------------+
	| Variable_name           | Value                       |
	+-------------------------+-----------------------------+
	| innodb_version          | 5.5.44                      |
	| protocol_version        | 10                          |
	| slave_type_conversions  |                             |
	| version                 | 5.5.44-0ubuntu0.14.04.1-log |
	| version_comment         | (Ubuntu)                    |
	| version_compile_machine | x86_64                      |
	| version_compile_os      | debian-linux-gnu            |
	+-------------------------+-----------------------------+

	mysql> SHOW VARIABLES LIKE 'performance_schema';
	+--------------------+-------+
	| Variable_name      | Value |
	+--------------------+-------+
	| performance_schema | ON    |
	+--------------------+-------+

I have even checked and the column is there:

	mysql> describe performance_schema.events_waits_summary_global_by_event_name;
	+----------------+---------------------+------+-----+---------+-------+
	| Field          | Type                | Null | Key | Default | Extra |
	+----------------+---------------------+------+-----+---------+-------+
	| EVENT_NAME     | varchar(128)        | NO   |     | NULL    |       |
	| COUNT_STAR     | bigint(20) unsigned | NO   |     | NULL    |       |
	| SUM_TIMER_WAIT | bigint(20) unsigned | NO   |     | NULL    |       |
	| MIN_TIMER_WAIT | bigint(20) unsigned | NO   |     | NULL    |       |
	| AVG_TIMER_WAIT | bigint(20) unsigned | NO   |     | NULL    |       |
	| MAX_TIMER_WAIT | bigint(20) unsigned | NO   |     | NULL    |       |
	+----------------+---------------------+------+-----+---------+-------+

Any idea of what can be wrong?

**Comment by sjmudd** [comment]
Hmm. Sorry to have not noticed your message earlier. I've not tried on 5.5 and I think therefore that it's ps-top is unlikely to work as the 5.5 P_S tables are very basic. That said. I'll check and if I can make this work for you I'll make a patch. If not I'll at least see what's wrong.

**Comment by sjmudd** [comment]
Also please note the comments in: https://github.com/sjmudd/ps-top/blob/master/README.md which state "...which collects information from MySQL 5.6+'s performance_schema database...". In any case I'll take a quick look and see.

**Comment by scorredoira** [comment]
Hi Simon, sorry I didnt ser the note. I will wait until ubuntu upgrades the MySQL packages. Thank you!
El 21 nov. 2015 1:27 p. m., Simon J Mudd <notifications@github.com> escribió:Also please note the comments in: https://github.com/sjmudd/ps-top/blob/master/README.md which state "...which collects information from MySQL 5.6+'s performance_schema database...". In any case I'll take a quick look and see.

**Comment by sjmudd** [comment]
Ok, then I'll ignore this for now. However, I was under the impression that Ubuntu did provide a 5.6 or later version of MySQL. Perhaps it depends on the version of Ubuntu you are running?

**Comment by scorredoira** [comment]
yes, the latest ubuntu 15.10 does, but I use the LTS (14.04) which still provides 5.5.46

**Comment by sjmudd** [comment]
Well Oracle provide later (free community) binaries for CentOS. I'd expect them to work for Ubuntu/Debian too. I gave up using the OS supplied binaries a long time ago as they tend to be hopelessly out of date. Maybe you can do the same?

**Comment by scorredoira** [comment]
It turns out that they also provide the 5.6 version if you specify it "apt-get install mysql-server-5.6". I will be able to try the tool finally :)

**Comment by scorredoira** [comment]
It works fine, very nice tool.
